#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sudoku.Resource", IsApplication=true)]

namespace Sudoku
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int main_menu_margin = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int new_game_button = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int options_button = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int solve_button = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int statistics_button = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Solve = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Statistics = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int new_game_button = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int options_button = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int solve_button = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int statistics_button = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
